//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialTracking.Types
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AssemblyItemProduct
    {
        [ScaffoldColumn(false)]
        public int AssemblyItemID { get; set; }
        [ScaffoldColumn(false)]
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AssemblyItem AssemblyItem { get; set; }
        public virtual Product Product { get; set; }
    }
}
