//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialTracking.Types
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.POOrderDetails = new HashSet<POOrderDetail>();
        }
    
        [ScaffoldColumn(false)]
        public int OrderDetailID { get; set; }
        [ScaffoldColumn(false)]
        public int OrderRequestID { get; set; }
        [ScaffoldColumn(false)]
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public int OrderStatusID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> InventoryID { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual OrderRequest OrderRequest { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POOrderDetail> POOrderDetails { get; set; }
    }
}
