//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialTracking.Types
{
    using System;
    using System.Collections.Generic;
    
    public partial class POOrderDetail
    {
        public int POOrderDetailID { get; set; }
        public int POOrderID { get; set; }
        public int OrderDetailID { get; set; }
        public string PONumber { get; set; }
        public int OrderStatusID { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual POOrder POOrder { get; set; }
    }
}
