//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialTracking.Types
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ShippingOrder
    {
        [ScaffoldColumn(false)]
        public int ShipperID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public System.DateTime DateShipped { get; set; }
        public System.DateTime DateEstimatedArrival { get; set; }
        public Nullable<System.DateTime> DateArrived { get; set; }
        public int OrderStatusID { get; set; }
        public int ShippingOrderID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
